### ISSUE TITLE
file does not match a filename rule

### ISSUE THREAD

**Issue by lsilvam** [YPetremann/obsidian-ruled-template#1]
Hi. 

Thank you for making this plugin; it was something I was looking up to for a while.

However, I might be missing something here on how to use it. Maybe you can help me out. 
I already use regex expression with [auto file mover](https://github.com/farux/obsidian-auto-note-mover), and it is working as expected. Yet, in your plugin says that the file does not match any rule. Why? Do I need to specify that I am using Regex and not glob?

Here is an example. The regex expression I am using to sort literature notes with filename as `@Author2023` is this `^@(.+)?\d{4}$`. When I created a new file the note is sorted but it does not pull the template I associated with this expression. 

Thank you very much for your time.

Cheers 

---- 
OS: windows 10 22H2
obsidian v 1.4.2
Rule Template v 1.1.0

**Comment by lsilvam** [comment]
> Do I need to specify that I am using Regex and not glob?

I see that it does (https://github.dev/YPetremann/obsidian-ruled-template/blob/885419592d3ff4180ca91243ee16cfe7f3310f96/src/main.ts#L58). 

Yet even after changing to `/^@(.+)?\d{4}$/` it keeps not matching.  I also tried `/^@(.+)?\d{4}(.md)$/` and still does not work.

**Comment by lsilvam** [comment]
It seems that the expression is recognized when out of the path string. See the attached figures.
<img width="582" alt="Obsidian_cRZhncuTgm" src="https://github.com/YPetremann/obsidian-ruled-template/assets/53966548/4c961355-c5bb-47eb-a2fe-4ad9bd9e59aa">
<img width="578" alt="Obsidian_rX1FNbCQVs" src="https://github.com/YPetremann/obsidian-ruled-template/assets/53966548/ece623f6-4869-4111-9e97-6a499546bd50">

**Comment by YPetremann** [comment]
Yes I see, in fact it doesn't match the filename but the full path, so try :
`/^(.*/)?@(.+)?\d{4}(.md)$/`

**Comment by lsilvam** [comment]
> /^(.*/)?@(.+)?\d{4}(.md)$/

it works. Ok, it needs the whole path. 

Found another unexpected behavior. When to template was loaded it did not run code like `{{date:YYYYMMDD}}`, it just copied and paste whatever text was in the note. So the end result in the new note was `{{date:YYYYMMDD}}` instead of `20230811`.

**Comment by YPetremann** [comment]
> Found another unexpected behavior. When to template was loaded it did not run code like `{{date:YYYYMMDD}}`, it just copied and paste whatever text was in the note. So the end result in the new note was `{{date:YYYYMMDD}}` instead of `20230811`.

Moved to #2, please post details about the issue
